INFO:     87.80.49.90:0 - "GET /api/airports?q=Dhaka HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q= HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=Qa HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=BA HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=B HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q= HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=E HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=EK HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=E HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q= HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=R HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=Rya HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=Ry HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q=R HTTP/1.1" 200 OK
INFO:     87.80.49.90:0 - "GET /api/airlines?q= HTTP/1.1" 200 OK
2025-08-16 17:12:01,205 INFO âœ… Created cheap alert 2 for user 1
INFO:     87.80.49.90:0 - "POST /create_alert HTTP/1.1" 302 Found
INFO:     87.80.49.90:0 - "GET /dashboard?alert_created=1 HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 403, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/routing.py", line 75, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/fastapi/routing.py", line 302, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/fastapi/routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/main.py", line 2400, in dashboard
    return templates.TemplateResponse("dashboard.html", {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/templating.py", line 210, in TemplateResponse
    return _TemplateResponse(
           ^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/templating.py", line 41, in __init__
    content = template.render(context)
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/workspaces/dynamic-scraper/templates/dashboard.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/workspaces/dynamic-scraper/templates/base.html", line 126, in top-level template code
    {% block content %}{% endblock %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/templates/dashboard.html", line 123, in block 'content'
    <a href="{{url_for('upgrade')}}" class="btn btn-warning btn-block mb-2">
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/templating.py", line 127, in url_for
    return request.url_for(name, **path_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/requests.py", line 187, in url_for
    url_path = url_path_provider.url_path_for(name, **path_params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/dynamic-scraper/.conda/lib/python3.11/site-packages/starlette/routing.py", line 663, in url_path_for
    raise NoMatchFound(name, path_params)
starlette.routing.NoMatchFound: No route exists for name "upgrade" and params "".
